# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:sMT+n8gUZ/ftAsxQDIoprmTF4T/0bbyPWm3QJhhhaTc=,iv:ktQ67TyevvXIV8jB2zan5XAfxqwAFWR5a5rRsPBKJxI=,tag:S8tdxz0v/tUPzSM1Yi/Q0w==,type:str]
sops:
  age:
    - recipient: age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRV29rcGFHU0dHQlNlY3Ju
        L2hIVkh3YTY2TFVSejdqZ285ejdxTWNoaWpRCmw5b1Q5OS9mUlpNdU9yRG9zeGI0
        dUlGOWVUeXBRZlBPZ3M2bGcyakZiTG8KLS0tIFZ6RERnQnlhOFV5bm9ObGtFMzFl
        NnA1aVJxYS9aT0FRdEQrUWdrejNTQXMKBcBB5ZPPlyVmjkZmJtjh7dZJ0Ac/hKTz
        At5r4gyN7//T8hUwWHIwIF0JUNHknE4sxKap02v67wdJiJabAcr3SQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-28T04:41:04Z"
  mac: ENC[AES256_GCM,data:i8JExi45je9u7Xy7aVj6CwS68t2l6MIUa0v7YND8lJEdDRfIO5r83hetfJO9n4DwDKzNAqpBuoYLFXtgNTFPsnZoi87ilpmmG/zoE/XhEjM3/HdrgmDUsiaSuni7lVRO36rfYqLigji366+g6xIR4QPDPFivjh0x+wb3bHSF0Q4=,iv:zyvCmkjgRVWSX31EoB6fyK8CP01fI4uSSBWupXIiZks=,tag:2zM5yVMBkG5PNXnTSuLCiA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
