# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Ps/lGVTWRzlgKx/meck/hxZvp0MzsOFGCFYF9D9LEroPywAQovsJ46/BNK96xRqAIsJK4j7ZoFzeWG6MX9EeGbHmG/lfpO7QR/G2rPoWCwNdBY60447FZeeOI5i+P47IyoBD1QHzOcr+VyJyZO/1qbSMo3UtYZ2d9/HqtvvyPHUom/Di2ZrzS2M6hYjngorGtx0kqwOU4h5JCRcAiTxBVUD9ra6fol0HL53i+e6QDoz0QxXt,iv:mIxsHYkfU4ncqGFvBfSDJlq6NHg4ah7mUpP42PFnn4A=,tag:nqxIaw1EosoSt/amd5wCrg==,type:str]
sops:
  age:
    - recipient: age1p8c94xufr4jgnwt67nagw4n0cwycvyqn66f38yn4tv434edcv43qa3ns3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MzBFVXRZSWtUcGFjY2R5
        ck1PS2JXUURSWkJFN0NsMTNZb1JLQk1pNTJNClJhRm1wMStKSWNNM1AxSTdBZlpD
        SXNLcE9SVktHMGhYY1BRZ2FUUDJybm8KLS0tIGNJSHNhQzVpSHViSm5BMGRlVm9Z
        UW9IMnBlMG5xQVZrVGk5L2Z2akNORDAKtskyW/84yFveFpNyMytIUvkx6e9DRVcr
        jBWeEpnmDUFbua5iglBetIKV8qvGiwdq6iz92V+kxcybd8/jV+weZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-28T04:41:04Z"
  mac: ENC[AES256_GCM,data:27YaOBxQ1z9beGD6GJ436sqV9Gb5JeF7JlmR1Xdv6Bb6/Z4omndg4CjOuF2swr/wyJqmae79x7QZUP/wfE9to9e+3mi5DPS6f4DGp88EPwHyccniDKpACpK629zORyxndP8yTknxoTFTTGfNUzxh9413upbtLVkXFtH85yJO1Ts=,iv:Gv2I2RwkgLRHBT/mrMTA6D3l4YBmqg4AEN7d64xC1Xs=,tag:oC8+sptVoeHD6i/Yzi5Qaw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
